name = "LEMONÂ³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.41.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05fcb5dab3a46b8af9ed5add8298024bacca9d7df7f7c452261e6763bc796387"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
