name = "LEMONÂ³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.41.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a5b74821110acc4fe382c3981ced830cf74c3d8bc550b932c48a2c4b10f93d0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
