name = "LEMONÂ³"
author = "SkywardMC, OffsetMonkey538, Isaiah"
version = "1.41.1+1.21.11.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "757f6d003555e31c335513c12e92a7ee9d56578cdcf383aee95becca10242448"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
